### PR TITLE
avoid adding multiple instances in DI

### PR DESCRIPTION
**Pull request by ghidello**
Hi and thanks for your library.

I was experimenting with it for a library of my own and i started wondering what would happen to an user registering both my library and yours: would the DI complain about the double registration? Apparently it does not but the services collection count increases by two when i register both my and your library (probably the duplication is resolved during the DI system build and, yes, I should study this topic a lot more).

Anyway, as a quick fix, I changed the AddSingleton calls with the TryAdd counterparts and... It works on my pc! :smile:

Oh, I also updated the nuget dependencies version because I wasn't able to install the original versions.

Thanks again for your library, it works like a charm!

Ciao

### CODE REVIEW

**Comment by LunicLynx** [comment]
Hey @ghidello,
nice catch!

I think it could even be better. Isn't there an extension method `TryAddSingleton` ([MSDN](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.extensions.servicecollectiondescriptorextensions.tryaddsingleton?view=aspnetcore-2.1#Microsoft_Extensions_DependencyInjection_Extensions_ServiceCollectionDescriptorExtensions_TryAddSingleton__1_Microsoft_Extensions_DependencyInjection_IServiceCollection_))?

**Comment by ghidello** [comment]
Did I mention that I should study the topic a lot more? :smile:
I’m not at the pc right now so you can close this pr and go ahead with the better option.

Thanks again!

**Comment by LunicLynx** [comment]
I'll take the PR and change the line later.

**Comment by LunicLynx** [comment]
I'll take the PR and change the line later.
Do you need it for 0.4.0 as well? 

Thanks

**Comment by ghidello** [comment]
I'm in the process of moving to 0.5.0 too so I personally don't need version 0.4.0.
Thanks again!

**Comment by LunicLynx** [comment]
publish in progress 0.5.0-preview3

**Pull request merged**
